/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Sleep Notification 
 #	author : miyako
 #	2016/01/28
 #
 # --------------------------------------------------------------------------------*/

#include <IOKit/ps/IOPowerSources.h>
#include <IOKit/ps/IOPSKeys.h>

// --- Notification
void SN_Set_sleep_method(sLONG_PTR *pResult, PackagePtr pParams);
void SN_Get_sleep_method(sLONG_PTR *pResult, PackagePtr pParams);

// --- Information
void Get_battery_warning_level(sLONG_PTR *pResult, PackagePtr pParams);
void GET_POWER_INFORMATION(sLONG_PTR *pResult, PackagePtr pParams);

void listenerInit(void);
void listenerLoop(void);
void listenerLoopStart(void);
void listenerLoopFinish(void);
void listenerLoopExecute(void);

//internal variable

typedef PA_long32 process_number_t;
typedef PA_long32 process_stack_size_t;
typedef PA_long32 method_id_t;
typedef PA_long32 event_id_t;
typedef PA_Unichar* process_name_t;